### ISSUE TITLE
String for webservice type=discart is empty

### ISSUE THREAD

**Issue by Angelinas1** [marcelveldt/script.module.metadatautils#2]
Marcel AnimatedArt working but need to add this two line in kodidb.py
Now with code `http://localhost:52307/getartwork&amp;title=$INFO[Window.Property(Title)]&amp;type=discart` Art doesent excist......
`ERROR: CCurlFile::Stat - Failed: Timeout was reached(28) for http://localhost:52307/getartwork&title=Logan&type=discart`
add this please ROW 665 IN kodidb.py
```
            if art.get("discart"):
                art["discart"] = get_clean_image(art["discart"])
            if art.get("clearart"):
                art["clearart"] = get_clean_image(art["clearart"])
```

**Comment by walterheisenberg** [comment]
I can confirm, this fix is working, but don't forget to add "clearlogo" also ;)

**Comment by marcelveldt** [comment]
fi will be available in next update version, provided later today or tomorrow.
