### ISSUE TITLE
Bypassing omdb calls

### ISSUE THREAD

**Issue by hablaras** [marcelveldt/script.module.metadatautils#21]
Hi Marcel,

Is there are way to set in any settings file that you want to bypass calls to omdb?

My log is full of these messages because I don't have (or want) to "buy" a key:
 
**01:22:42.342 T:1237316592  NOTICE: script.module.metadatautils --> Rate limiter active for omdbapi.com - delaying request with 2 seconds - Configure a personal API key in the settings to get rid of this message and the delay.**

I am using the Eminence 2 MOD skin, that uses skin.helper.service and script.module.metadatautils.

Or could I just delete the **omdb.py** file in the script.module.metadatautils/lib/helpers folder? :)

ps Sorry for asking here, but the official Kodi forum is already down for 6+ days...

**Comment by marcelveldt** [comment]
those messages will only be logged when the cache is empty so it will disappear
also there should be a free api key option too by now

That said, the messages will be in your log, does it harm ?

In any case, do not delete the omdb.py file because things will crash badly if you do so.

**Comment by hablaras** [comment]
Thanks for the response. 

I was investigating why it takes about 10 seconds per movie to scan it to the database and then I found the above message in the log.

So, no, it doesn't harm, unless this:

**delaying request with 2 seconds**

delays _each_ movie scan. Then re-scanning a complete library of 1000 movies adds 2000 seconds to the process. 

Or does this task on a separate thread (in parallel) in the background?

**Comment by marcelveldt** [comment]
No it doesn't have any impact on your scan progress. This is only about the import of additional info.
Great that you fixed it properly with getting a personal key
