### ISSUE TITLE
[Bug] CPU Load rises to 100%, Network traffic also rises 

### ISSUE THREAD

**Issue by malvinas2** [marcelveldt/script.module.metadatautils#28]
Hello, 

I am using Krypton 17.6 together with the Titan skin and after the upgrade to version 1.0.19 of the Metadata and Artwork addon, the CPU load rises up to 100%, the htpc receives data from the NAS with nearly 70 Mbit/s and the fan is going mad. This behaviour continues even when being in idle state, for example in the main menu of Kodi without playing any media. 
(EDIT: I am sure, that this addon must be the reason for this behaviour because I coincidentally created an image of the whole system one week ago. Within this week just 5 addons got an update and as soon as I install the upgrade of metadatautils this behaviour occurs)

https://imgur.com/loIRMvI
https://imgur.com/S1WDhi1

Log: https://pastebin.com/SZ0UQT9u

**Comment by malvinas2** [comment]
I reinstalled the whole Titan skin and also recreated the MySQL-database and now it is working.

**Comment by malvinas2** [comment]
I am sorry, but I have to reopen this issue... 
I experienced this error again: One or two minutes after the start of Kodi the CPU load rises up to nearly 100% and the network interface receives a huge amount of data. I restarted Kodi and the htpc several times, nothing changed. Then I deleted the addon-directory and userdata-directory of metadatautils and restarted Kodi and everything works normal, even now after 3 hours uptime.

**Comment by marcelveldt** [comment]
I think you've hit some sort of edge case because I'm unable to reproduce. While all the artwork fetching and such is pretty heavy for simple devices like pi's it shouldn't hurt that much as you described. Please let me know if you might run into this again so we can do some debugging. In any case, provide the kodi logfile at that time.

**Comment by malvinas2** [comment]
You're right, it seems to be pure coincidence that the trouble stopped just in the moment after I deleted the addon. 
My apologies for the false alarm.
